// <auto-generated />
using System;
using GameReviewHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameReviewHub.Data.Migrations
{
    [DbContext(typeof(GameReviewHubDbContext))]
    [Migration("20260118195210_InitialSeedData")]
    partial class InitialSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameReviewHub.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A sprawling role-playing adventure in the Dungeons & Dragons universe, featuring deep narrative, tactical combat, and rich character progression.",
                            Developer = "Larian Studios",
                            ReleaseDate = new DateTime(2023, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Baldur's Gate 3"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A fast-paced roguelike action game where players fight to escape the Underworld, combining tight combat with evolving storytelling.",
                            Developer = "Supergiant Games",
                            ReleaseDate = new DateTime(2020, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hades"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A wuxia-inspired open-world action-adventure RPG set in a fantastical version of historical China, blending martial arts combat with exploration.",
                            Developer = "Everstone Studio",
                            ReleaseDate = new DateTime(2025, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Where Winds Meet"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A visually stunning platform adventure about a young guardian spirit on a touching journey to save a dying forest filled with heart and challenge.",
                            Developer = "Moon Studios",
                            ReleaseDate = new DateTime(2015, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ori and the Blind Forest"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A beloved roguelike deckbuilder that blends strategic card combat with procedural levels, challenging players to ascend the mysterious Spire.",
                            Developer = "Mega Crit",
                            ReleaseDate = new DateTime(2019, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Slay the Spire"
                        });
                });

            modelBuilder.Entity("GameReviewHub.Models.GameGenre", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("GamesGenres");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            GameId = 1,
                            GenreId = 2
                        },
                        new
                        {
                            GameId = 1,
                            GenreId = 3
                        },
                        new
                        {
                            GameId = 1,
                            GenreId = 4
                        },
                        new
                        {
                            GameId = 2,
                            GenreId = 5
                        },
                        new
                        {
                            GameId = 2,
                            GenreId = 6
                        },
                        new
                        {
                            GameId = 3,
                            GenreId = 5
                        },
                        new
                        {
                            GameId = 3,
                            GenreId = 1
                        },
                        new
                        {
                            GameId = 3,
                            GenreId = 4
                        },
                        new
                        {
                            GameId = 3,
                            GenreId = 7
                        },
                        new
                        {
                            GameId = 4,
                            GenreId = 8
                        },
                        new
                        {
                            GameId = 4,
                            GenreId = 4
                        },
                        new
                        {
                            GameId = 5,
                            GenreId = 6
                        },
                        new
                        {
                            GameId = 5,
                            GenreId = 9
                        },
                        new
                        {
                            GameId = 5,
                            GenreId = 10
                        });
                });

            modelBuilder.Entity("GameReviewHub.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "RPG"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Turn-Based"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tactical"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Roguelike"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Open World"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Platformer"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Deckbuilder"
                        });
                });

            modelBuilder.Entity("GameReviewHub.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Pros:\n- Deep role-playing systems and meaningful choices\n- Strong companion writing and voice acting\n- Great tactical combat variety\n\nCons:\n- Can feel overwhelming early on\n- Occasional pacing dips in long sessions\n\nOverall:\n- An exceptional RPG that rewards exploration and experimentation.",
                            CreatedOn = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 1,
                            Score = 10,
                            Title = "A modern RPG benchmark"
                        },
                        new
                        {
                            Id = 2,
                            Body = "Pros:\n- Tight combat and excellent weapon variety\n- Fantastic music, art direction, and character dialogue\n- Progression feels rewarding run after run\n\nCons:\n- Repetition can set in if you binge it\n- Some builds depend heavily on luck\n\nOverall:\n- One of the best roguelikes, with story that actually motivates retries.",
                            CreatedOn = new DateTime(2020, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 2,
                            Score = 9,
                            Title = "Fast, stylish, endlessly replayable"
                        },
                        new
                        {
                            Id = 3,
                            Body = "Pros:\n- Beautiful world design and strong wuxia atmosphere\n- Martial arts combat feels unique and expressive\n- Exploration and movement are very satisfying\n\nCons:\n- Performance can be inconsistent\n- Some systems feel under-explained\n\nOverall:\n- An ambitious action RPG that could be great with refinement and updates.",
                            CreatedOn = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 3,
                            Score = 8,
                            Title = "Huge potential, needs polish"
                        },
                        new
                        {
                            Id = 4,
                            Body = "Pros:\n- Stunning visuals and memorable soundtrack\n- Fluid movement and satisfying platforming\n- Strong emotional storytelling\n\nCons:\n- A few sections have sharp difficulty spikes\n- Combat is simpler than the platforming\n\nOverall:\n- A gorgeous adventure that’s worth experiencing for its world and feel.",
                            CreatedOn = new DateTime(2015, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 4,
                            Score = 9,
                            Title = "Beautiful and emotional platforming"
                        },
                        new
                        {
                            Id = 5,
                            Body = "Pros:\n- Deep strategy with tons of build variety\n- Highly replayable with meaningful decisions\n- Excellent balance and difficulty progression\n\nCons:\n- Visual presentation is minimalistic\n- Runs can swing based on RNG\n\nOverall:\n- A top-tier deckbuilder that stays fresh for hundreds of runs.",
                            CreatedOn = new DateTime(2019, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 5,
                            Score = 9,
                            Title = "Strategic deckbuilding perfection"
                        });
                });

            modelBuilder.Entity("GameReviewHub.Models.GameGenre", b =>
                {
                    b.HasOne("GameReviewHub.Models.Game", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameReviewHub.Models.Genre", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("GameReviewHub.Models.Review", b =>
                {
                    b.HasOne("GameReviewHub.Models.Game", "Game")
                        .WithMany("Reviews")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameReviewHub.Models.Game", b =>
                {
                    b.Navigation("GameGenres");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("GameReviewHub.Models.Genre", b =>
                {
                    b.Navigation("GameGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
